"""
This type stub file was generated by pyright.
"""

from airflow.exceptions import AirflowException

class EcsTaskFailToStart(Exception):
    """Raise when ECS tasks fail to start AFTER processing the request."""

    def __init__(self, message: str) -> None: ...
    def __reduce__(self):  # -> tuple[type[EcsTaskFailToStart], str]:
        """Return ECSTask state and its message."""
        ...

class EcsOperatorError(Exception):
    """Raise when ECS cannot handle the request."""

    def __init__(self, failures: list, message: str) -> None: ...
    def __reduce__(self):  # -> tuple[type[EcsOperatorError], tuple[list[Any], str]]:
        """Return EcsOperator state and a tuple of failures list and message."""
        ...

class S3HookUriParseFailure(AirflowException):
    """When parse_s3_url fails to parse URL, this error is thrown."""

    ...
