repos:
  - repo: "https://github.com/psf/black"
    rev: 22.10.0
    hooks:
    - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.265
    hooks:
    - id: ruff
      args:
        [
          "--fix",
          "--exit-non-zero-on-fix"
        ]

  - repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.1
    hooks:
      - id: typos

# https://github.com/compilerla/conventional-pre-commit
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

