site_name: Dagcellent Docs
site_url: http://localhost:8000

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - def_list
  - meta
  - footnotes
  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - markdown.extensions.attr_list
  - pymdownx.details

theme:
  name: material
  custom_dir: docs/custom_theme
  favicon: images/icons/logo.svg
  logo: images/icons/logo.svg
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins: 
  - search
  - git-revision-date-localized
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            modernize_annotations: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true
            merge_init_into_class: true
            parameter_headings: true
            show_root_heading: false
            docstring_options:
              ignore_init_summary: true
            show_source: false
            filters:
              - "!^_"
              - "^__init__$"
              # Hide some methods that are part of Airflow Operator interface
              - "!^execute$"

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - About: about.md
  - Contributing: contributing.md
  - Reference:
      - "reference/index.md"
      - Operators: "reference/operators.md"
      - Dag:
          - "reference/dag.md"
      - Data utilities:
          - "reference/data_utils.md"
