"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import TYPE_CHECKING

from airflow.io.typedef import Properties
from fsspec import AbstractFileSystem

if TYPE_CHECKING: ...
log = ...
_BUILTIN_SCHEME_TO_FS: dict[
    str, Callable[[str | None, Properties], AbstractFileSystem]
] = ...

def get_fs(
    scheme: str, conn_id: str | None = ..., storage_options: Properties | None = ...
) -> AbstractFileSystem:
    """
    Get a filesystem by scheme.

    :param scheme: the scheme to get the filesystem for
    :return: the filesystem method
    :param conn_id: the airflow connection id to use
    :param storage_options: the storage options to pass to the filesystem
    """
    ...

def has_fs(scheme: str) -> bool:
    """
    Check if a filesystem is available for a scheme.

    :param scheme: the scheme to check
    :return: True if a filesystem is available for the scheme
    """
    ...
