"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import TYPE_CHECKING

from airflow.models import DagModel, DagRun

"""Experimental APIs."""
if TYPE_CHECKING: ...

def check_and_get_dag(dag_id: str, task_id: str | None = ...) -> DagModel:
    """Check DAG existence and in case it is specified that Task exists."""
    ...

def check_and_get_dagrun(dag: DagModel, execution_date: datetime) -> DagRun:
    """Get DagRun object and check that it exists."""
    ...
