"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

import boto3
from botocore.waiter import Waiter

if TYPE_CHECKING: ...

class BaseBotoWaiter:
    """
    Used to create custom Boto3 Waiters.

    For more details, see airflow/providers/amazon/aws/waiters/README.md
    """

    def __init__(
        self, client: boto3.client, model_config: dict, deferrable: bool = ...
    ) -> None: ...
    def waiter(self, waiter_name: str) -> Waiter: ...
