"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable

from airflow.providers.openlineage.extractors.base import BaseExtractor, OperatorLineage

class PythonExtractor(BaseExtractor):
    """
    Extract executed source code and put it into SourceCodeJobFacet.

    This extractor provides visibility on what particular task does by extracting
    executed source code and putting it into SourceCodeJobFacet. It does not extract
    datasets yet.

    :meta private:
    """

    @classmethod
    def get_operator_classnames(cls) -> list[str]: ...
    def get_source_code(self, callable: Callable) -> str | None: ...
    def extract(self) -> OperatorLineage | None: ...
