"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from airflow.models.connection import Connection
from airflow.secrets import BaseSecretsBackend
from airflow.utils.session import provide_session
from sqlalchemy.orm import Session

"""Objects relating to sourcing connections from metastore database."""
if TYPE_CHECKING: ...

class MetastoreBackend(BaseSecretsBackend):
    """Retrieves Connection object and Variable from airflow metastore database."""

    @provide_session
    def get_connection(
        self, conn_id: str, session: Session = ...
    ) -> Connection | None: ...
    @provide_session
    def get_connections(
        self, conn_id: str, session: Session = ...
    ) -> list[Connection]: ...
    @provide_session
    def get_variable(self, key: str, session: Session = ...) -> str | None:
        """
        Get Airflow Variable from Metadata DB.

        :param key: Variable Key
        :return: Variable Value
        """
        ...
