"""
This type stub file was generated by pyright.
"""

from uuid import UUID

NIL_UUID = ...

def generate_uuid(*values: str | None, namespace: UUID = ...) -> str:
    """
    Convert input values to deterministic UUID string representation.

    This function is only intended to generate a hash which used as an identifier, not for any security use.

    Generates a UUID v5 (SHA-1 + Namespace) for each value provided,
    and this UUID is used as the Namespace for the next element.

    If only one non-None value is provided to the function, then the result of the function
    would be the same as result of ``uuid.uuid5``.

    All ``None`` values are replaced by NIL UUID.  If it only one value is provided then return NIL UUID.

    :param namespace: Initial namespace value to pass into the ``uuid.uuid5`` function.
    """
    ...
