"""
This type stub file was generated by pyright.
"""

from typing import Any

from airflow.hooks.base import BaseHook

"""Hook for additional Package Indexes (Python)."""

class PackageIndexHook(BaseHook):
    """Specify package indexes/Python package sources using Airflow connections."""

    conn_name_attr = ...
    default_conn_name = ...
    conn_type = ...
    hook_name = ...
    def __init__(self, pi_conn_id: str = ..., **kwargs) -> None: ...
    @staticmethod
    def get_ui_field_behaviour() -> dict[str, Any]:
        """Return custom field behaviour."""
        ...

    def get_conn(self) -> Any:
        """Return connection for the hook."""
        ...

    def get_connection_url(self) -> Any:
        """Return a connection URL with embedded credentials."""
        ...

    def test_connection(self) -> tuple[bool, str]:
        """Test connection to package index url."""
        ...
