apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagcellent-docs
  labels:
    app: dagcellent-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagcellent-docs
  template:
    metadata:
      labels:
        app: dagcellent-docs
    spec:
      containers:
      - name: dagcellent-docs
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/dataplatform/dagcellent-docs:latest
        imagePullPolicy: Always
        ports:
---
apiVersion: v1
kind: Service
metadata:
  name: dagcellent-docs
spec:
  type: NodePort
  selector:
    app: dagcellent-docs
  ports:
   - port: 80
     targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sample-ingressroute
spec:
  entryPoints:
  - web
  routes:
    - kind: Rule
      match: Host(`compass.dfds.cloud`) && PathPrefix(`/dagcellent`)
      services:
        - kind: Service
          name: dagcellent-docs  # the name of the service
          port: 80          # the port exposed by the service
          passHostHeader: true    # Any other options, for instance passHostHeader

