"""
This type stub file was generated by pyright.
"""

from airflow.models.base import Base

class LogTemplate(Base):
    """
    Changes to ``log_filename_template`` and ``elasticsearch_id``.

    This table is automatically populated when Airflow starts up, to store the
    config's value if it does not match the last row in the table.
    """

    __tablename__ = ...
    id = ...
    filename = ...
    elasticsearch_id = ...
    created_at = ...
    def __repr__(self) -> str: ...
