"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from airflow.auth.managers.base_auth_manager import ResourceMethod

if TYPE_CHECKING: ...
_MAP_METHOD_NAME_TO_FAB_ACTION_NAME: dict[ResourceMethod, str] = ...

def get_fab_action_from_method_map():  # -> dict[ResourceMethod, str]:
    """Return the map associating a method to a FAB action."""
    ...

def get_method_from_fab_action_map():  # -> dict[str, str]:
    """Return the map associating a FAB action to a method."""
    ...
