"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from airflow.jobs.job import Job
from airflow.serialization.pydantic.job import JobPydantic
from airflow.utils.session import provide_session
from sqlalchemy.orm import Session

if TYPE_CHECKING: ...

class BaseJobRunner:
    """Abstract class for job runners to derive from."""

    job_type = ...
    def __init__(self, job: Job) -> None: ...
    @provide_session
    def heartbeat_callback(self, session: Session = ...) -> None:
        """
        Execute callback during heartbeat.

        This method can be overwritten by the runners.
        """
        ...

    @classmethod
    @provide_session
    def most_recent_job(cls, session: Session = ...) -> Job | JobPydantic | None:
        """Return the most recent job of this type, if any, based on last heartbeat received."""
        ...
