"""
This type stub file was generated by pyright.
"""

def tmp_configuration_copy(chmod=..., include_env=..., include_cmds=...):  # -> str:
    """
    Return a path for a temporary file including a full copy of the configuration settings.

    :param include_env: Should the value of configuration from ``AIRFLOW__``
        environment variables be included or not
    :param include_cmds: Should the result of calling any *_cmd config be
        set (True, default), or should the _cmd options be left as the
        command to run (False)
    :return: a path to a temporary file
    """
    ...
