"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple

class AirflowParsingContext(NamedTuple):
    """
    Context of parsing for the DAG.

    If these values are not None, they will contain the specific DAG and Task ID that Airflow is requesting to
    execute. You can use these for optimizing dynamically generated DAG files.
    """

    dag_id: str | None
    task_id: str | None
    ...

_AIRFLOW_PARSING_CONTEXT_DAG_ID = ...
_AIRFLOW_PARSING_CONTEXT_TASK_ID = ...

def get_parsing_context() -> AirflowParsingContext:
    """Return the current (DAG) parsing context info."""
    ...
