"""
This type stub file was generated by pyright.
"""

import hashlib
from typing import TYPE_CHECKING

from _typeshed import ReadableBuffer

if TYPE_CHECKING: ...

def md5(__string: ReadableBuffer = ...) -> hashlib._Hash:
    """
    Safely allows calling the ``hashlib.md5`` function when ``usedforsecurity`` is disabled in configuration.

    :param __string: The data to hash. Default to empty str byte.
    :return: The hashed value.
    """
    ...
