"""
This type stub file was generated by pyright.
"""

from functools import cache

@cache
def getfqdn(name=...):  # -> str:
    """
    Get fully qualified domain name from name.

    An empty argument is interpreted as meaning the local host.
    """
    ...

def get_host_ip_address():  # -> str:
    """Fetch host ip address."""
    ...

def get_hostname():  # -> Any:
    """Fetch the hostname using the callable from config or use `airflow.utils.net.getfqdn` as a fallback."""
    ...
