"""
This type stub file was generated by pyright.
"""

import logging
from collections.abc import Callable
from typing import TypeVar, overload

F = TypeVar("F", bound=Callable)
MAX_DB_RETRIES = ...

def run_with_db_retries(
    max_retries: int = ..., logger: logging.Logger | None = ..., **kwargs
):  # -> Retrying:
    """Return Tenacity Retrying object with project specific default."""
    ...

@overload
def retry_db_transaction(*, retries: int = ...) -> Callable[[F], F]: ...
@overload
def retry_db_transaction(_func: F) -> F: ...
def retry_db_transaction(
    _func: Callable | None = ..., *, retries: int = ..., **retry_kwargs
):  # -> Callable[..., Callable[..., Any]] | Callable[..., Any]:
    """
    Retry functions in case of ``DBAPIError`` from DB.

    It should not be used with ``@provide_session``.
    """
    ...
