"""
This type stub file was generated by pyright.
"""

from typing import Generic, TypeVar

T = TypeVar("T")

class Singleton(type, Generic[T]):
    """Metaclass that allows to implement singleton pattern."""

    _instances: dict[Singleton[T], T] = ...
    def __call__(cls: Singleton[T], *args, **kwargs) -> T: ...
