"""
This type stub file was generated by pyright.
"""

"""Common utility functions with strings."""

def get_random_string(length=..., choices=...):  # -> str:
    """Generate random string."""
    ...

TRUE_LIKE_VALUES = ...

def to_boolean(astring: str | None) -> bool:
    """Convert a string to a boolean."""
    ...
