"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING, Any, BinaryIO, TextIO

"""
Use libyaml for YAML dump/load operations where possible.

If libyaml is available we will use it -- it is significantly faster.

This module delegates all other properties to the yaml module, so it can be used as:

.. code-block:: python
    import airflow.utils.yaml as yaml

And then be used directly in place of the normal python module.
"""
if TYPE_CHECKING: ...

def safe_load(stream: bytes | str | BinaryIO | TextIO) -> Any:
    """Like yaml.safe_load, but use the C libyaml for speed where we can."""
    ...

def dump(data: Any, **kwargs) -> str:
    """Like yaml.safe_dump, but use the C libyaml for speed where we can."""
    ...

def __getattr__(name):  # -> Any:
    ...
