"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass(frozen=True, order=True)
class DagDependency:
    """
    Dataclass for representing dependencies between DAGs.

    These are calculated during serialization and attached to serialized DAGs.
    """

    source: str
    target: str
    dependency_type: str
    dependency_id: str | None = ...
    @property
    def node_id(self):  # -> str:
        """Node ID for graph rendering."""
        ...
