"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Serialized DAG and BaseOperator."""

def serialize_template_field(
    template_field: Any, name: str
) -> str | dict | list | int | float:
    """
    Return a serializable representation of the templated field.

    If ``templated_field`` contains a class or instance that requires recursive
    templating, store them as strings. Otherwise simply return the field as-is.
    """
    ...
