"""
This type stub file was generated by pyright.
"""

from typing import Any

HEALTHY = ...
UNHEALTHY = ...

def get_airflow_health() -> dict[str, Any]:
    """Get the health for Airflow metadatabase, scheduler and triggerer."""
    ...
