"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from airflow.utils.session import provide_session
from sqlalchemy.orm import Session

"""Delete DAGs APIs."""
if TYPE_CHECKING: ...
log = ...

@provide_session
def delete_dag(
    dag_id: str, keep_records_in_log: bool = ..., session: Session = ...
) -> int:
    """
    Delete a DAG by a dag_id.

    :param dag_id: the dag_id of the DAG to delete
    :param keep_records_in_log: whether keep records of the given dag_id
        in the Log table in the backend database (for reasons like auditing).
        The default value is True.
    :param session: session used
    :return count of deleted dags
    """
    ...
