"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from pluggy._hooks import _HookRelay

if TYPE_CHECKING: ...
log = ...
_listener_manager: ListenerManager | None = ...

class ListenerManager:
    """Manage listener registration and provides hook property for calling them."""

    def __init__(self) -> None: ...
    @property
    def has_listeners(self) -> bool: ...
    @property
    def hook(self) -> _HookRelay:
        """Return hook, on which plugin methods specified in spec can be called."""
        ...

    def add_listener(self, listener):  # -> None:
        ...
    def clear(self):  # -> None:
        """Remove registered plugins."""
        ...

def get_listener_manager() -> ListenerManager:
    """Get singleton listener manager."""
    ...
