"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from airflow.callbacks.callback_requests import CallbackRequest

if TYPE_CHECKING: ...

class BaseCallbackSink:
    """Base class for Callbacks Sinks."""

    def send(self, callback: CallbackRequest) -> None:
        """Send callback for execution."""
        ...
