"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from multiprocessing.connection import Connection as MultiprocessingConnection
from typing import TYPE_CHECKING

from airflow.callbacks.base_callback_sink import BaseCallbackSink
from airflow.callbacks.callback_requests import CallbackRequest

if TYPE_CHECKING: ...

class PipeCallbackSink(BaseCallbackSink):
    """
    Class for sending callbacks to DagProcessor using pipe.

    It is used when DagProcessor is not executed in standalone mode.
    """

    def __init__(
        self, get_sink_pipe: Callable[[], MultiprocessingConnection]
    ) -> None: ...
    def send(self, callback: CallbackRequest):  # -> None:
        """
        Send information about the callback to be executed by Pipe.

        :param callback: Callback request to be executed.
        """
        ...
