"""
This type stub file was generated by pyright.
"""

from flask.sessions import SecureCookieSessionInterface
from flask_session.sessions import SqlAlchemySessionInterface

class SessionExemptMixin:
    """Exempt certain blueprints/paths from autogenerated sessions."""

    def save_session(self, *args, **kwargs):  # -> None:
        """Prevent creating session from REST API and health requests."""
        ...

class AirflowDatabaseSessionInterface(SessionExemptMixin, SqlAlchemySessionInterface):
    """Session interface that exempts some routes and stores session data in the database."""

    ...

class AirflowSecureCookieSessionInterface(
    SessionExemptMixin, SecureCookieSessionInterface
):
    """Session interface that exempts some routes and stores session data in a signed cookie."""

    ...
