"""
This type stub file was generated by pyright.
"""

from logging import FileHandler
from logging.handlers import RotatingFileHandler
from typing import IO

def make_file_io_non_caching(io: IO[str]) -> IO[str]: ...

class NonCachingFileHandler(FileHandler):
    """
    An extension of FileHandler, advises the Kernel to not cache the file in PageCache when it is written.

    While there is nothing wrong with such cache (it will be cleaned when memory is needed), it
    causes ever-growing memory usage when scheduler is running as it keeps on writing new log
    files and the files are not rotated later on. This might lead to confusion for our users,
    who are monitoring memory usage of Scheduler - without realising that it is harmless and
    expected in this case.

    See https://github.com/apache/airflow/issues/14924

    Adding the advice to Kernel might help with not generating the cache memory growth in the first place.
    """

    ...

class NonCachingRotatingFileHandler(RotatingFileHandler):
    """
    An extension of RotatingFileHandler, advises the Kernel to not cache the file in PageCache when written.

    While there is nothing wrong with such cache (it will be cleaned when memory is needed), it
    causes ever-growing memory usage when scheduler is running as it keeps on writing new log
    files and the files are not rotated later on. This might lead to confusion for our users,
    who are monitoring memory usage of Scheduler - without realising that it is harmless and
    expected in this case.

    See https://github.com/apache/airflow/issues/27065

    Adding the advice to Kernel might help with not generating the cache memory growth in the first place.
    """

    ...
