"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from airflow.models.dagrun import DagRun

if TYPE_CHECKING: ...
hookspec = ...

@hookspec
def on_dag_run_running(dag_run: DagRun, msg: str):  # -> None:
    """Execute when dag run state changes to RUNNING."""
    ...

@hookspec
def on_dag_run_success(dag_run: DagRun, msg: str):  # -> None:
    """Execute when dag run state changes to SUCCESS."""
    ...

@hookspec
def on_dag_run_failed(dag_run: DagRun, msg: str):  # -> None:
    """Execute when dag run state changes to FAIL."""
    ...
