"""
This type stub file was generated by pyright.
"""

hookspec = ...

@hookspec
def on_new_dag_import_error(filename, stacktrace):  # -> None:
    """Execute when new dag import error appears."""
    ...

@hookspec
def on_existing_dag_import_error(filename, stacktrace):  # -> None:
    """Execute when existing dag import error appears."""
    ...
