"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from airflow.models.taskinstance import TaskInstance
from airflow.utils.state import TaskInstanceState
from sqlalchemy.orm.session import Session

if TYPE_CHECKING: ...
hookspec = ...

@hookspec
def on_task_instance_running(
    previous_state: TaskInstanceState | None,
    task_instance: TaskInstance,
    session: Session | None,
):  # -> None:
    """Execute when task state changes to RUNNING. previous_state can be None."""
    ...

@hookspec
def on_task_instance_success(
    previous_state: TaskInstanceState | None,
    task_instance: TaskInstance,
    session: Session | None,
):  # -> None:
    """Execute when task state changes to SUCCESS. previous_state can be None."""
    ...

@hookspec
def on_task_instance_failed(
    previous_state: TaskInstanceState | None,
    task_instance: TaskInstance,
    error: None | str | BaseException,
    session: Session | None,
):  # -> None:
    """Execute when task state changes to FAIL. previous_state can be None."""
    ...
