name: Documentation 
on:
    workflow_run:
      workflows: [CI]
      types: [completed]
      branches: [trunk]
permissions:
  contents: write

env:
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: dataplatform/apache-airflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocstrings mkdocstrings-python
          pip install -e .
      - run: mkdocs gh-deploy --force

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - run: |
        pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocstrings mkdocstrings-python
        pip install -e .
        mkdocs build
      name: Install docs dependencies and build static files

    - name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create and use a new builder instance
      run: |
        docker buildx create --name mybuilder --use

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./k8s/docs.Dockerfile
        push: true
        tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        builder: mybuilder
        cache-from: type=registry,ref=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:cache
        cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:cache
