"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

from airflow.models.baseoperator import BaseOperator

"""Sends lineage metadata to a backend."""
if TYPE_CHECKING: ...

class LineageBackend:
    """Sends lineage metadata to a backend."""

    def send_lineage(
        self,
        operator: BaseOperator,
        inlets: list | None = ...,
        outlets: list | None = ...,
        context: dict | None = ...,
    ):
        """
        Send lineage metadata to a backend.

        :param operator: the operator executing a transformation on the inlets and outlets
        :param inlets: the inlets to this operator
        :param outlets: the outlets from this operator
        :param context: the current context of the task instance
        """
        ...
